name: Build Vehicle Masters APK (Player Buff Only, Separate Install)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Extract project
        run: unzip VehicleMasters_FullProject_Android15_Lite.zip -d UnityProject

      - name: Set title, package, and buff player vehicle
        run: |
          # Set Unity project PlayerSettings for title & package
          SETTINGS_FILE=$(find UnityProject -type f -name "ProjectSettings.asset")
          if [ -n "$SETTINGS_FILE" ]; then
            sed -i 's/productName: .*/productName: Vehicle Masters/' "$SETTINGS_FILE"
            sed -i 's/packageName: .*/packageName: com.vehiclemasters.buff/' "$SETTINGS_FILE"
          fi
          
          # Buff player vehicle stats only
          find UnityProject -type f -name "*Player*.cs" -exec sed -i           -e 's/\(maxSpeed\s*=\s*\)\([0-9]*\)/echo "\1$((\2 + \2 * 30 / 100))"/ge'           -e 's/\(acceleration\s*=\s*\)\([0-9]*\)/echo "\1$((\2 + \2 * 25 / 100))"/ge'           -e 's/\(steerSensitivity\s*=\s*\)\([0-9]*\)/echo "\1$((\2 + \2 * 20 / 100))"/ge' {} +

      - name: Cache Unity
        uses: actions/cache@v3
        with:
          path: ~/.cache/unity
          key: ${{ runner.os }}-unity

      - name: Build Android APK
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.0f1
          targetPlatform: Android
          projectPath: UnityProject
          buildName: VehicleMasters_Android15_PlayerBuff
          buildPath: build

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: VehicleMasters_Android15_PlayerBuff
          path: build/*.apk
          
