name: Build Vehicle Masters APK (Player Buff Only, Separate Install)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 0️⃣ Free Disk Space (to avoid 'no space left' errors in Android builds)
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          large-packages: false

      # 1️⃣ Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4  # Updated to latest
        with:
          lfs: true

      # 2️⃣ Extract Project ZIP
      - name: Extract project
        run: |
          ls -la
          unzip -o VehicleMasters_FullProject_Android15_Lite.zip -d UnityProject
          ls -la UnityProject

      # 3️⃣ Validate Project Structure
      - name: Validate project
        run: |
          if [ ! -d "UnityProject/Assets" ]; then
            echo "Error: Assets folder not found in UnityProject!"
            exit 1
          fi
          echo "Project structure validated."

      # 4️⃣ Set Title, Package & Buff Player Vehicle
      - name: Set title, package, and buff player vehicle
        run: |
          SETTINGS_FILE=$(find UnityProject -type f -name "ProjectSettings.asset")
          if [ -n "$SETTINGS_FILE" ]; then
            sed -i 's/productName: .*/productName: Vehicle Masters/' "$SETTINGS_FILE"
            sed -i 's/packageName: .*/packageName: com.vehiclemasters.buff/' "$SETTINGS_FILE"
          else
            echo "Error: ProjectSettings.asset not found!"
            exit 1
          fi
          # Backup original files before modification
          find UnityProject -type f -name "*Player*.cs" | while read FILE; do
            if [ -f "$FILE" ]; then
              cp "$FILE" "${FILE}.bak"
              sed -i -E 's/(maxSpeed\s*=\s*)([0-9]+)/\1$(printf "%.0f" $(echo "\2 * 1.3" | bc))/' "$FILE"
              sed -i -E 's/(acceleration\s*=\s*)([0-9]+)/\1$(printf "%.0f" $(echo "\2 * 1.25" | bc))/' "$FILE"
              sed -i -E 's/(steerSensitivity\s*=\s*)([0-9]+)/\1$(printf "%.0f" $(echo "\2 * 1.2" | bc))/' "$FILE"
            else
              echo "Warning: $FILE not found, skipping buff."
            fi
          done

      # 5️⃣ Cache Unity
      - name: Cache Unity
        uses: actions/cache@v4  # Updated to latest
        with:
          path: ~/.cache/unity
          key: ${{ runner.os }}-unity

      # 6️⃣ Test Unity Project
      - name: Test Unity Project
        uses: game-ci/unity-test-runner@v4  # Updated to v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.0f1
          projectPath: UnityProject
          testMode: editmode

      # 7️⃣ Build Android APK
      - name: Build Android APK
        uses: game-ci/unity-builder@v4  # Updated to v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 2022.3.0f1
          targetPlatform: Android
          projectPath: UnityProject
          buildName: VehicleMasters_Android15_PlayerBuff
          buildsPath: build
          allowDirtyBuild: true

      # 8️⃣ Upload APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: VehicleMasters_Android15_PlayerBuff
          path: build/*.apk
